In [1]:
import numpy as np
from scipy.linalg import svd, eigh

M = np.array([
    [1,2],
    [2,1],
    [3,4],
    [4,3]
])

In [24]:
U, S, VT = svd(M,full_matrices=False)
print("U\n",U,end='\n\n')
print("S\n",S,end='\n\n')
print("Vt\n",VT,end='\n\n')
print("M\n", U@(S.reshape(1,-1).T*VT))



U
 [[-0.27854301  0.5       ]
 [-0.27854301 -0.5       ]
 [-0.64993368  0.5       ]
 [-0.64993368 -0.5       ]]

S
 [7.61577311 1.41421356]

Vt
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

M
 [[1. 2.]
 [2. 1.]
 [3. 4.]
 [4. 3.]]


In [45]:
A1 = M.T@M   #symmetry
print("A1\n",A1,end='\n\n')
Evals1, Evecs1 = eigh(A1)
Evals1 = sorted(Evals1, reverse=True)
Evecs1 = np.array([[Evecs1[0,1],Evecs1[0,0]],[Evecs1[1,1],Evecs1[1,0]]])
print("eigenvalues\n",Evals1,end='\n\n')
print("eigenvectors\n",Evecs1,end='\n\n')

A1
 [[30 28]
 [28 30]]

eigenvalues
 [58.0, 2.0]

eigenvectors
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]



In [44]:
A2 = M@M.T   #symmetry
print("A2\n",A2,end='\n\n')
Evals2, Evecs2 = eigh(A2)
Evals2 = sorted(Evals2, reverse=True)
Evecs2 = np.array([[Evecs2[0,1],Evecs2[0,0]],[Evecs2[1,1],Evecs2[1,0]]])
print("eigenvalues\n",Evals2,end='\n\n')
print("eigenvectors\n",Evecs2,end='\n\n')

A2
 [[ 5  4 11 10]
 [ 4  5 10 11]
 [11 10 25 24]
 [10 11 24 25]]

eigenvalues
 [58.00000000000002, 1.9999999999999973, 8.3552171924283e-15, 9.038791923008218e-16]

eigenvectors
 [[ 0.          0.82000841]
 [-0.79259392  0.21025857]]



In [46]:
# relation between sigular value and eigenvalue
# the square of each singular value is equal to eigenvalue
print("square of singular\n",S**2,end='\n\n')
print("eigenvalue1\n",Evals1)
print("eigenvalue2\n",Evals2)

square of singular
 [58.  2.]

eigenvalue1
 [58.0, 2.0]
eigenvalue2
 [58.00000000000002, 1.9999999999999973, 8.3552171924283e-15, 9.038791923008218e-16]


In [39]:
from sklearn.decomposition import PCA
print(M)
pca = PCA(n_components=2)
pca_A = pca.fit_transform(A)
print(pca_A)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[[1 2]
 [2 1]
 [3 4]
 [4 3]]
[[-1.41421356e+00  2.37213427e-17]
 [ 1.41421356e+00  2.37213427e-17]]
[1.00000000e+00 2.81351049e-34]
[2.00000000e+00 3.35470445e-17]
