In [3]:
import numpy as np
import math
x = np.array([64.,66.,68.,69.,73.])
y = np.array([580.,570.,590.,660.,600.])
z = np.array([29.,33.,37.,46.,55.])

m = np.array([x.mean(), y.mean(), z.mean()])
print(m)
print()

cov = np.stack([x,y,z]) - m.reshape(1,-1).T
x_u = np.array([66.,640.,44.]) - m
print(cov)

cov = (cov@cov.T)/(len(x)-1)
print(cov)
incov = np.linalg.inv(cov)
print(incov)

print(math.sqrt(x_u.reshape(1,-1) @ incov @ x_u.reshape(1,-1).T))
print(math.sqrt(4))
# print(incov.shape)
# print(x_u.reshape(1,-1).T.shape)

[ 68. 600.  40.]

[[ -4.  -2.   0.   1.   5.]
 [-20. -30. -10.  60.   0.]
 [-11.  -7.  -3.   6.  15.]]
[[  11.5    50.     34.75]
 [  50.   1250.    205.  ]
 [  34.75  205.    110.  ]]
[[ 3.68851865e+00  6.27308946e-02 -1.28214415e+00]
 [ 6.27308946e-02  2.21900278e-03 -2.39526742e-02]
 [-1.28214415e+00 -2.39526742e-02  4.58770977e-01]]
5.334540488762537
2.0


In [ ]:

# pca = PCA(n_components=3, svd_solver='randomized', random_state=42)

# # Assigning new features to the auto dataset and dropping compressed features
# df_auto_vis = pd.DataFrame(pca.fit_transform(df_auto), columns=["Vis1", "Vis2", "Vis3"])

# # 3D plots of clusters
# fig = plt.figure(figsize=(8, 6))
# ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=20, azim=60, auto_add_to_figure=False)
# fig.add_axes(ax)
# ax.scatter(df_auto_vis.iloc[:, 0], df_auto_vis.iloc[:, 1], df_auto_vis.iloc[:, 2], edgecolor='k')
# ax.w_xaxis.set_ticklabels([])
# ax.w_yaxis.set_ticklabels([])
# ax.w_zaxis.set_ticklabels([])
# ax.set_title('3D plot of KMeans Clustering')